name: Aptu Triage
description: Automatically triage GitHub issues and generate release notes using AI-powered analysis with aptu
author: Aptu Contributors

branding:
  icon: zap
  color: blue

inputs:
  github-token:
    description: GitHub token for API access
    required: true
  gemini-api-key:
    description: Google Gemini API key (from https://aistudio.google.com/apikey)
    required: false
  openrouter-api-key:
    description: OpenRouter API key (from https://openrouter.ai/keys)
    required: false
  groq-api-key:
    description: Groq API key (from https://console.groq.com/keys)
    required: false
  cerebras-api-key:
    description: Cerebras API key (from https://console.cerebras.ai/keys)
    required: false
  zai-api-key:
    description: Z.AI API key (from https://z.ai)
    required: false
  zenmux-api-key:
    description: ZenMux API key (from https://zenmux.ai)
    required: false
  model:
    description: Model to use for analysis (provider-specific, see docs/CONFIGURATION.md)
    required: false
    default: ''
  provider:
    description: AI provider to use (gemini, openrouter, groq, cerebras, zai, zenmux)
    required: false
    default: ''
  skip-labeled:
    description: Skip triage if issue already has both type and priority labels
    required: false
    default: 'false'
  dry-run:
    description: Run without making changes
    required: false
    default: 'false'
  apply-labels:
    description: Apply AI-suggested labels and milestone to the issue
    required: false
    default: 'true'
  no-comment:
    description: Skip posting triage comment to GitHub (only apply labels/milestone)
    required: false
    default: 'false'
  command:
    description: Command to run (issue or pr)
    required: false
    default: 'issue'
  subcommand:
    description: Subcommand to run (triage for issue, label or review for pr)
    required: false
    default: 'triage'
  reference:
    description: Reference for the command (issue/PR number or URL)
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Check if issue should be skipped
      id: check-skip
      shell: bash
      env:
        SKIP_LABELED: ${{ inputs.skip-labeled }}
        ISSUE_LABELS: ${{ toJson(github.event.issue.labels) }}
      run: |
        if [[ "$SKIP_LABELED" == "true" ]]; then
          LABEL_COUNT=$(echo "$ISSUE_LABELS" | jq 'length')
          if [[ $LABEL_COUNT -gt 0 ]]; then
            echo "skip=true" >> $GITHUB_OUTPUT
            echo "Issue already has labels, skipping triage"
            exit 0
          fi
        fi
        echo "skip=false" >> $GITHUB_OUTPUT

    - name: Set environment variables
      if: steps.check-skip.outputs.skip != 'true'
      shell: bash
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
        INPUT_GEMINI_API_KEY: ${{ inputs.gemini-api-key }}
        INPUT_OPENROUTER_API_KEY: ${{ inputs.openrouter-api-key }}
        INPUT_GROQ_API_KEY: ${{ inputs.groq-api-key }}
        INPUT_CEREBRAS_API_KEY: ${{ inputs.cerebras-api-key }}
        INPUT_ZAI_API_KEY: ${{ inputs.zai-api-key }}
        INPUT_ZENMUX_API_KEY: ${{ inputs.zenmux-api-key }}
        INPUT_MODEL: ${{ inputs.model }}
        INPUT_PROVIDER: ${{ inputs.provider }}
        INPUT_DRY_RUN: ${{ inputs.dry-run }}
        INPUT_APPLY_LABELS: ${{ inputs.apply-labels }}
        INPUT_NO_COMMENT: ${{ inputs.no-comment }}
      run: |
        # Set shared environment variables for subsequent steps
        # Values from inputs (originally secrets) are auto-masked by GitHub
        echo "GITHUB_TOKEN=$INPUT_GITHUB_TOKEN" >> "$GITHUB_ENV"
        echo "GEMINI_API_KEY=$INPUT_GEMINI_API_KEY" >> "$GITHUB_ENV"
        echo "OPENROUTER_API_KEY=$INPUT_OPENROUTER_API_KEY" >> "$GITHUB_ENV"
        echo "GROQ_API_KEY=$INPUT_GROQ_API_KEY" >> "$GITHUB_ENV"
        echo "CEREBRAS_API_KEY=$INPUT_CEREBRAS_API_KEY" >> "$GITHUB_ENV"
        echo "ZAI_API_KEY=$INPUT_ZAI_API_KEY" >> "$GITHUB_ENV"
        echo "ZENMUX_API_KEY=$INPUT_ZENMUX_API_KEY" >> "$GITHUB_ENV"
        echo "APTU_AI__MODEL=$INPUT_MODEL" >> "$GITHUB_ENV"
        echo "APTU_AI__PROVIDER=$INPUT_PROVIDER" >> "$GITHUB_ENV"
        echo "DRY_RUN=$INPUT_DRY_RUN" >> "$GITHUB_ENV"
        echo "APPLY_LABELS=$INPUT_APPLY_LABELS" >> "$GITHUB_ENV"
        echo "NO_COMMENT=$INPUT_NO_COMMENT" >> "$GITHUB_ENV"

    - name: Download aptu binary
      if: steps.check-skip.outputs.skip != 'true'
      shell: bash
      run: |
        set -e
        
        # Get latest v0.x.x release from GitHub API (authenticated to avoid rate limits)
        APTU_VERSION=$(gh api repos/clouatre-labs/aptu/releases --jq '[.[] | select(.tag_name | startswith("v0."))] | first | .tag_name' | sed 's/^v//')
        echo "Latest aptu v0.x version: $APTU_VERSION"
        
        BINARY_URL="https://github.com/clouatre-labs/aptu/releases/download/v${APTU_VERSION}/aptu-${APTU_VERSION}-x86_64-unknown-linux-musl.tar.gz"
        TEMP_DIR=$(mktemp -d)
        
        echo "Downloading aptu from $BINARY_URL"
        curl -sL "$BINARY_URL" -o "$TEMP_DIR/aptu.tar.gz"
        tar -xzf "$TEMP_DIR/aptu.tar.gz" -C "$TEMP_DIR"
        
        # Make binary executable and move to PATH
        chmod +x "$TEMP_DIR/aptu"
        mkdir -p "$HOME/.local/bin"
        mv "$TEMP_DIR/aptu" "$HOME/.local/bin/aptu"
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
        rm -rf "$TEMP_DIR"
        echo "aptu v$APTU_VERSION installed successfully"

    - name: Run aptu issue triage
      if: github.event_name == 'issues' && steps.check-skip.outputs.skip != 'true'
      shell: bash
      env:
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        REPO: ${{ github.repository }}
      run: |
        set -e
        
        ISSUE_REF="${REPO}#${ISSUE_NUMBER}"
        ARGS="--yes"
        
        if [[ "$DRY_RUN" == "true" ]]; then
          ARGS="$ARGS --dry-run"
        fi
        
        if [[ "$APPLY_LABELS" == "true" ]]; then
          ARGS="$ARGS --apply"
        fi
        
        if [[ "$NO_COMMENT" == "true" ]]; then
          ARGS="$ARGS --no-comment"
        fi
        
        echo "Running: aptu issue triage $ARGS $ISSUE_REF"
        aptu issue triage $ARGS "$ISSUE_REF"

    - name: Run aptu PR label
      if: github.event_name == 'pull_request'
      shell: bash
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
        REPO: ${{ github.repository }}
      run: |
        set -e
        
        PR_REF="${REPO}#${PR_NUMBER}"
        ARGS=""
        
        if [[ "$DRY_RUN" == "true" ]]; then
          ARGS="$ARGS --dry-run"
        fi
        
        echo "Running: aptu pr label $ARGS $PR_REF"
        aptu pr label $ARGS "$PR_REF"

    - name: Run aptu PR review
      if: github.event_name == 'pull_request'
      continue-on-error: true  # Non-blocking - AI review is advisory
      shell: bash
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
        REPO: ${{ github.repository }}
      run: |
        set -e
        
        PR_REF="${REPO}#${PR_NUMBER}"
        ARGS="--comment --yes"
        
        if [[ "$DRY_RUN" == "true" ]]; then
          ARGS="$ARGS --dry-run"
        fi
        
        echo "Running: aptu pr review $ARGS $PR_REF"
        aptu pr review $ARGS "$PR_REF"

    - name: Run aptu release
      if: github.event_name == 'release'
      shell: bash
      env:
        TAG: ${{ github.event.release.tag_name }}
        REPO: ${{ github.repository }}
      run: |
        set -e
        
        ARGS="--update"
        
        if [[ "$DRY_RUN" == "true" ]]; then
          ARGS="$ARGS --dry-run"
        fi
        
        echo "Running: aptu release --repo $REPO $ARGS $TAG"
        aptu release --repo "$REPO" $ARGS "$TAG"
