name: ✨ Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement to Aptu!
        
        **Before submitting**, please search [existing feature requests](https://github.com/clouatre-labs/aptu/issues?q=is%3Aissue+label%3Aenhancement) to avoid duplicates.

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: |
        What problem does this feature solve? What use case would it unlock?
      placeholder: |
        As a contributor, I want to... so that I can...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how you'd like this feature to work.
      placeholder: |
        Add a `--filter` flag to `aptu issue list` that allows...
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered?
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or references?
    validations:
      required: false

  - type: checkboxes
    id: duplicate-check
    attributes:
      label: Duplicate Check
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
