// SPDX-License-Identifier: Apache-2.0

//! Triage status detection for GitHub issues.
//!
//! This module provides utilities to check whether an issue has already been triaged,
//! either through labels or Aptu-generated comments.

use crate::ai::types::{
    CommentSeverity, IssueDetails, PrFile, PrReviewComment, PrReviewResponse, TriageResponse,
};
use crate::utils::is_priority_label;
use sha2::{Digest, Sha256};
use std::fmt::Write;
use tracing::debug;

/// Signature string used to identify Aptu-generated triage comments
pub const APTU_SIGNATURE: &str = "Generated by Aptu";

/// Status of whether an issue has already been triaged
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TriageStatus {
    /// Whether the issue has a type label (bug, enhancement, etc.)
    pub has_type_label: bool,
    /// Whether the issue has a priority label (p0-p4, priority: high/medium/low)
    pub has_priority_label: bool,
    /// Whether the issue has an Aptu-generated comment
    pub has_aptu_comment: bool,
    /// List of labels that indicate triage status
    pub label_names: Vec<String>,
}

impl TriageStatus {
    /// Create a new `TriageStatus`.
    #[must_use]
    pub fn new(
        has_type_label: bool,
        has_priority_label: bool,
        has_aptu_comment: bool,
        label_names: Vec<String>,
    ) -> Self {
        Self {
            has_type_label,
            has_priority_label,
            has_aptu_comment,
            label_names,
        }
    }

    /// Check if the issue has been triaged (has both type and priority labels, or Aptu comment).
    #[must_use]
    pub fn is_triaged(&self) -> bool {
        (self.has_type_label && self.has_priority_label) || self.has_aptu_comment
    }
}

/// Check if a label is a type label (bug, enhancement, documentation, etc.).
fn is_type_label(label: &str) -> bool {
    const TYPE_LABELS: &[&str] = &[
        "bug",
        "enhancement",
        "documentation",
        "question",
        "good first issue",
        "help wanted",
        "duplicate",
        "invalid",
        "wontfix",
        "triaged",
        "needs-triage",
        "status: triaged",
    ];
    TYPE_LABELS.contains(&label)
}

/// Renders a labeled list section in markdown format.
fn render_list_section_markdown(
    title: &str,
    items: &[String],
    empty_msg: &str,
    numbered: bool,
) -> String {
    let mut output = String::new();
    let _ = writeln!(output, "### {title}\n");
    if items.is_empty() {
        let _ = writeln!(output, "{empty_msg}");
    } else if numbered {
        for (i, item) in items.iter().enumerate() {
            let _ = writeln!(output, "{}. {}", i + 1, item);
        }
    } else {
        for item in items {
            let _ = writeln!(output, "- {item}");
        }
    }
    output.push('\n');
    output
}

/// Render the complexity section into markdown, if present.
fn render_complexity_markdown(output: &mut String, triage: &TriageResponse) {
    use crate::ai::types::ComplexityLevel;
    let Some(c) = &triage.complexity else {
        return;
    };
    output.push_str("### Complexity\n\n");
    let level_str = match c.level {
        ComplexityLevel::Low => "Low",
        ComplexityLevel::Medium => "Medium",
        ComplexityLevel::High => "High",
    };
    let loc_str = c
        .estimated_loc
        .map(|l| format!(" (~{l} LOC)"))
        .unwrap_or_default();
    let _ = writeln!(output, "**Level:** {level_str}{loc_str}");
    if c.affected_areas.is_empty() {
        output.push('\n');
    } else {
        let areas: Vec<String> = c.affected_areas.iter().map(|a| format!("`{a}`")).collect();
        let _ = writeln!(output, "Affected: {}\n", areas.join(", "));
    }
    if let Some(rec) = &c.recommendation
        && !rec.is_empty()
    {
        let _ = writeln!(output, "**Recommendation:** {rec}\n");
    }
}

/// Renders triage response as markdown for posting to GitHub.
///
/// Generates pure markdown without terminal colors. This is the core rendering
/// function used by both CLI and FFI layers.
///
/// # Arguments
///
/// * `triage` - The triage response to render
///
/// # Returns
///
/// A markdown string suitable for posting as a GitHub comment.
#[must_use]
pub fn render_triage_markdown(triage: &TriageResponse) -> String {
    let mut output = String::new();

    // Header
    output.push_str("## Triage Summary\n\n");
    output.push_str(&triage.summary);
    output.push_str("\n\n");

    // Labels (always show in markdown for maintainers)
    let labels: Vec<String> = triage
        .suggested_labels
        .iter()
        .map(|l| format!("`{l}`"))
        .collect();
    output.push_str(&render_list_section_markdown(
        "Suggested Labels",
        &labels,
        "None",
        false,
    ));

    // Suggested Milestone
    if let Some(milestone) = &triage.suggested_milestone
        && !milestone.is_empty()
    {
        output.push_str("### Suggested Milestone\n\n");
        output.push_str(milestone);
        output.push_str("\n\n");
    }

    // Suggested Milestone
    if let Some(milestone) = &triage.suggested_milestone
        && !milestone.is_empty()
    {
        output.push_str("### Suggested Milestone\n\n");
        output.push_str(milestone);
        output.push_str("\n\n");
    }

    // Complexity assessment
    render_complexity_markdown(&mut output, triage);

    // Questions
    output.push_str(&render_list_section_markdown(
        "Clarifying Questions",
        &triage.clarifying_questions,
        "None needed",
        true,
    ));

    // Duplicates
    output.push_str(&render_list_section_markdown(
        "Potential Duplicates",
        &triage.potential_duplicates,
        "None found",
        false,
    ));

    // Related issues with reason blockquote
    if !triage.related_issues.is_empty() {
        output.push_str("### Related Issues\n\n");
        for issue in &triage.related_issues {
            let _ = writeln!(output, "- **#{}** - {}", issue.number, issue.title);
            let _ = writeln!(output, "  > {}\n", issue.reason);
        }
    }

    // Status note (if present)
    if let Some(status_note) = &triage.status_note
        && !status_note.is_empty()
    {
        output.push_str("### Status\n\n");
        output.push_str(status_note);
        output.push_str("\n\n");
    }

    // Contributor guidance (if present)
    if let Some(guidance) = &triage.contributor_guidance {
        output.push_str("### Contributor Guidance\n\n");
        let beginner_label = if guidance.beginner_friendly {
            "**Beginner-friendly**"
        } else {
            "**Advanced**"
        };
        let _ = writeln!(output, "{beginner_label}\n");
        let _ = writeln!(output, "{}\n", guidance.reasoning);
    }

    // Implementation approach
    if let Some(approach) = &triage.implementation_approach
        && !approach.is_empty()
    {
        output.push_str("### Implementation Approach\n\n");
        for line in approach.lines() {
            let _ = writeln!(output, "  {line}");
        }
        output.push('\n');
    }

    // Signature
    output.push_str("---\n");
    output.push('*');
    output.push_str(APTU_SIGNATURE);
    output.push('*');
    output.push('\n');

    output
}

/// Render a `ReleaseNotesResponse` to markdown format.
///
/// Check if an issue has already been triaged.
///
/// Returns `TriageStatus` indicating whether the issue has both type and priority labels,
/// or has an Aptu-generated comment.
pub fn check_already_triaged(issue: &IssueDetails) -> TriageStatus {
    let has_type_label = issue.labels.iter().any(|label| is_type_label(label));
    let has_priority_label = issue.labels.iter().any(|label| is_priority_label(label));

    let label_names: Vec<String> = issue
        .labels
        .iter()
        .filter(|label| is_type_label(label) || is_priority_label(label))
        .cloned()
        .collect();

    // Check for Aptu signature in comments
    let has_aptu_comment = issue
        .comments
        .iter()
        .any(|comment| comment.body.contains(APTU_SIGNATURE));

    if has_type_label || has_priority_label || has_aptu_comment {
        debug!(
            has_type_label = has_type_label,
            has_priority_label = has_priority_label,
            has_aptu_comment = has_aptu_comment,
            labels = ?label_names,
            "Issue triage status detected"
        );
    }

    TriageStatus::new(
        has_type_label,
        has_priority_label,
        has_aptu_comment,
        label_names,
    )
}

/// HTML marker embedded in every rendered inline review comment body so existing
/// comments can be identified without resolving the bot identity (GitHub App
/// installation tokens cannot use `current().user()`).
pub const REVIEW_COMMENT_MARKER: &str = "<!-- APTU_REVIEW_COMMENT -->";

/// Closing suffix of every HTML comment marker embedded in rendered bodies.
/// Shared by hash extraction and stripping so marker parsing stays consistent.
const HTML_COMMENT_END: &str = "-->";

/// Prefix of the HTML comment that carries the SHA-256 content hash of the
/// review comment (`<!-- APTU_COMMENT_HASH:<hex> -->`). Embedded immediately
/// after [`REVIEW_COMMENT_MARKER`] so dedup can compare semantic content
/// instead of rendered bytes; the hash covers only the comment text, severity,
/// and suggested code, never the rendering format.
pub const APTU_COMMENT_HASH_PREFIX: &str = "<!-- APTU_COMMENT_HASH:";

/// Computes the SHA-256 content hash (lowercase hex) over the semantic content
/// of a review comment: text, severity, and suggested code. Fields are encoded
/// with an 8-byte big-endian length prefix each so adversarial content (e.g.
/// embedded NUL bytes) cannot shift field boundaries or collide two distinct
/// semantic values. `suggested_code` additionally carries a presence
/// discriminant byte (0 for `None`, 1 for `Some`) so `None` and `Some("")` —
/// semantically different values — hash differently. Rendered format is
/// intentionally excluded so renderer-only changes do not trigger updates.
#[must_use]
pub fn comment_content_hash(comment: &PrReviewComment) -> String {
    fn hash_field(hasher: &mut Sha256, field: &str) {
        let bytes = field.as_bytes();
        hasher.update(u64::try_from(bytes.len()).unwrap_or(u64::MAX).to_be_bytes());
        hasher.update(bytes);
    }
    let mut hasher = Sha256::new();
    hash_field(&mut hasher, &comment.comment);
    hash_field(&mut hasher, &format!("{:?}", comment.severity));
    match &comment.suggested_code {
        None => hasher.update([0_u8]),
        Some(code) => {
            hasher.update([1_u8]);
            hash_field(&mut hasher, code);
        }
    }
    let digest = hasher.finalize();
    let mut hex = String::with_capacity(digest.len() * 2);
    for byte in digest {
        let _ = write!(hex, "{byte:02x}");
    }
    hex
}

/// Extracts the stored content hash from a previously rendered comment body.
/// The marker is searched directly after [`REVIEW_COMMENT_MARKER`] at the body
/// start so HTML-comment-like text inside suggestion blocks cannot be
/// misparsed. Returns `None` for legacy bodies posted before the hash marker
/// existed.
#[must_use]
pub fn extract_comment_hash(body: &str) -> Option<String> {
    let rest = body.trim_start().strip_prefix(REVIEW_COMMENT_MARKER)?;
    let rest = rest.trim_start().strip_prefix(APTU_COMMENT_HASH_PREFIX)?;
    let end = rest.find(HTML_COMMENT_END)?;
    let hash = rest[..end].trim();
    if hash.is_empty() {
        None
    } else {
        Some(hash.to_string())
    }
}

/// Marker prefix embedded in the PR review summary comment so it can be found
/// and deduplicated on later runs. The full marker carries the head commit SHA:
/// `<!-- APTU_REVIEW:<sha> -->`.
pub const REVIEW_SUMMARY_MARKER_PREFIX: &str = "<!-- APTU_REVIEW:";

/// A parsed Aptu review summary marker.
///
/// `sha` is `None` for the legacy SHA-less marker (`<!-- APTU_REVIEW -->`),
/// which is always treated as stale so the summary is refreshed.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AptuSummaryMarker {
    /// Head commit SHA recorded when the summary was posted, if any.
    pub sha: Option<String>,
}

/// Parses the `<!-- APTU_REVIEW:<sha> -->` summary marker from a comment body.
///
/// Returns `None` when the body does not carry an Aptu review summary marker.
/// The legacy SHA-less form (`<!-- APTU_REVIEW -->`) parses to `sha: None` and
/// is treated as stale by callers so the summary is updated in place.
#[must_use]
pub fn parse_aptu_summary_marker(body: &str) -> Option<AptuSummaryMarker> {
    let trimmed = body.trim_start();
    // Legacy SHA-less marker has no colon separator; treat it as stale.
    if trimmed.starts_with("<!-- APTU_REVIEW -->") {
        return Some(AptuSummaryMarker { sha: None });
    }
    let rest = trimmed.strip_prefix(REVIEW_SUMMARY_MARKER_PREFIX)?;
    let end = rest.find("-->")?;
    let sha = rest[..end].trim();
    if sha.is_empty() {
        Some(AptuSummaryMarker { sha: None })
    } else {
        Some(AptuSummaryMarker {
            sha: Some(sha.to_string()),
        })
    }
}

/// Removes the content-hash marker line from a rendered body, producing the
/// legacy-style rendering used to compare against bodies posted before the
/// hash marker existed. Bodies without the hash marker are returned unchanged.
#[must_use]
pub fn strip_comment_hash(body: &str) -> String {
    let Some(start) = body.find(APTU_COMMENT_HASH_PREFIX) else {
        return body.to_string();
    };
    let Some(rel_end) = body[start..].find(HTML_COMMENT_END) else {
        return body.to_string();
    };
    let mut out = String::with_capacity(body.len());
    out.push_str(&body[..start]);
    out.push_str(body[start + rel_end + 3..].trim_start_matches('\n'));
    out
}

/// Formats an inline PR review comment body.
///
/// Prepends a severity badge derived from the comment severity. When the
/// comment includes `suggested_code`, appends a GitHub suggestion block
/// that renders as a one-click "Apply suggestion" button in the PR diff view.
#[must_use]
pub fn render_pr_review_comment_body(comment: &PrReviewComment) -> String {
    let mut body = String::from(REVIEW_COMMENT_MARKER);
    body.push('\n');
    body.push_str(APTU_COMMENT_HASH_PREFIX);
    body.push_str(&comment_content_hash(comment));
    body.push_str(" -->\n");
    body.push_str(severity_badge(&comment.severity));
    body.push(' ');
    body.push_str(&comment.comment);
    if let Some(code) = &comment.suggested_code
        && !code.is_empty()
    {
        body.push_str("\n\n```suggestion\n");
        body.push_str(code);
        body.push_str("\n```");
    }
    body
}

/// Emoji badge plus a text label for each severity. The text label keeps the
/// severity readable in screen readers, plain-text email, and non-rendered
/// views where emoji color alone carries no meaning.
fn severity_badge(severity: &CommentSeverity) -> &'static str {
    match severity {
        CommentSeverity::Issue => "🔴 Issue:",
        CommentSeverity::Warning => "🟠 Warning:",
        CommentSeverity::Suggestion => "💡 Suggestion:",
        CommentSeverity::Info => "🔵 Info:",
    }
}

/// Renders one collapsible `<details>` section with a bullet list.
///
/// Returns nothing when `items` is empty so empty sections are omitted
/// entirely from the rendered body.
fn render_collapsible_section(body: &mut String, title: &str, items: &[String]) {
    if items.is_empty() {
        return;
    }
    body.push_str(&format!("\n<details>\n<summary>{title}</summary>\n\n"));
    for item in items {
        let _ = writeln!(body, "- {item}");
    }
    body.push_str("\n</details>\n");
}

/// Renders the PR review summary comment body for posting to GitHub.
///
/// This is the single summary surface: the rendered summary lives ONLY here, as
/// an issue comment whose body starts with the
/// `<!-- APTU_REVIEW:<head_sha> -->` HTML comment so it can be deduplicated on
/// re-runs: an unchanged head SHA means the summary is skipped, a changed SHA
/// means it is patched in place. The PR review body itself is rendered
/// separately by [`render_pr_review_review_body`] and never contains the
/// summary.
#[must_use]
pub fn render_pr_review_markdown(review: &PrReviewResponse, head_sha: &str) -> String {
    let verdict_badge = verdict_badge(&review.verdict);

    let mut body = format!(
        "{}{} -->\n## Aptu Review\n\n**{}** — {}\n",
        REVIEW_SUMMARY_MARKER_PREFIX, head_sha, verdict_badge, review.summary
    );

    render_structured_sections(&mut body, review);

    body.push_str("\n---\n\n<sub>Posted by [aptu](https://github.com/clouatre-labs/aptu)</sub>\n");

    body
}

/// Maximum number of rows shown in the per-file walkthrough table before the
/// remaining files are collapsed into an "and N more" tail line.
const FILE_WALKTHROUGH_MAX_ROWS: usize = 20;

/// Renders the per-file walkthrough table (File | Diff) for the PR review body.
///
/// Rows are sorted by descending churn (additions + deletions) and carry stats
/// only (`+N −N`); no patches or AI-generated content. Removed and renamed
/// files render with whatever counts exist (including `+0 −0`). Returns `None`
/// when `files` is empty so the whole section is omitted.
/// Escapes a filename so it cannot corrupt the Markdown table structure or
/// inject rendered content: pipe characters are escaped (`|` -> `\|`),
/// carriage returns and line feeds are stripped, and backticks are escaped to
/// prevent inline code spans.
fn escape_table_cell(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    for c in name.chars() {
        match c {
            '\r' | '\n' => {}
            '\\' => out.push_str("\\\\"),
            '|' => out.push_str("\\|"),
            '`' => out.push_str("\\`"),
            _ => out.push(c),
        }
    }
    out
}

fn render_file_walkthrough(files: &[PrFile]) -> Option<String> {
    if files.is_empty() {
        return None;
    }

    let mut sorted: Vec<&PrFile> = files.iter().collect();
    sorted.sort_by_key(|f| std::cmp::Reverse(f.additions.saturating_add(f.deletions)));

    let mut table = String::from("\n### Files Changed\n\n| File | Diff |\n|---|---|\n");
    for f in sorted.iter().take(FILE_WALKTHROUGH_MAX_ROWS) {
        let _ = writeln!(
            table,
            "| {} | +{} −{} |",
            escape_table_cell(&f.filename),
            f.additions,
            f.deletions
        );
    }
    if sorted.len() > FILE_WALKTHROUGH_MAX_ROWS {
        let _ = writeln!(
            table,
            "| ... and {} more | |",
            sorted.len() - FILE_WALKTHROUGH_MAX_ROWS
        );
    }

    Some(table)
}

/// Renders the PR review body for posting to GitHub.
///
/// The review body carries only non-summary content (the verdict badge,
/// structured concerns/strengths/suggestions sections, and a per-file
/// walkthrough table with diff stats only); the rendered summary lives solely
/// in the deduplicated marker issue comment produced by
/// [`render_pr_review_markdown`].
#[must_use]
pub fn render_pr_review_review_body(review: &PrReviewResponse, files: &[PrFile]) -> String {
    let verdict_badge = verdict_badge(&review.verdict);
    let mut body = format!("## Aptu Review\n\n{verdict_badge}\n");

    render_structured_sections(&mut body, review);

    if let Some(table) = render_file_walkthrough(files) {
        body.push_str(&table);
    }

    body.push_str("\n---\n\n<sub>Posted by [aptu](https://github.com/clouatre-labs/aptu)</sub>\n");

    body
}

/// Renders the structured concerns/strengths/suggestions sections shared by
/// the summary comment and the review body, in a fixed order (Concerns,
/// Strengths, Suggestions) so both surfaces stay predictable. Concerns are
/// always rendered as a heading; strengths and suggestions are secondary and
/// collapsed inside `<details>` blocks. Empty sections are omitted entirely.
fn render_structured_sections(body: &mut String, review: &PrReviewResponse) {
    if !review.concerns.is_empty() {
        body.push_str("\n### Concerns\n\n");
        for c in &review.concerns {
            let _ = writeln!(body, "- {c}");
        }
    }
    render_collapsible_section(body, "Strengths", &review.strengths);
    render_collapsible_section(body, "Suggestions", &review.suggestions);
}

fn verdict_badge(verdict: &str) -> &'static str {
    match verdict {
        "approve" => "✅ Approved",
        "request_changes" | "request-changes" => "❌ Request Changes",
        _ => "💬 Comments",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ai::types::{CommentSeverity, IssueComment};

    fn create_test_issue(labels: Vec<String>, comments: Vec<IssueComment>) -> IssueDetails {
        IssueDetails::builder()
            .owner("test".to_string())
            .repo("repo".to_string())
            .number(1)
            .title("Test issue".to_string())
            .body("Test body".to_string())
            .labels(labels)
            .comments(comments)
            .url("https://github.com/test/repo/issues/1".to_string())
            .build()
    }

    #[test]
    fn test_no_triage() {
        let issue = create_test_issue(vec![], vec![]);
        let status = check_already_triaged(&issue);
        assert!(!status.is_triaged());
        assert!(!status.has_type_label);
        assert!(!status.has_priority_label);
        assert!(!status.has_aptu_comment);
        assert!(status.label_names.is_empty());
    }

    #[test]
    fn test_type_label_only() {
        let labels = vec!["bug".to_string()];
        let issue = create_test_issue(labels, vec![]);
        let status = check_already_triaged(&issue);
        assert!(!status.is_triaged());
        assert!(status.has_type_label);
        assert!(!status.has_priority_label);
        assert!(!status.has_aptu_comment);
        assert_eq!(status.label_names.len(), 1);
    }

    #[test]
    fn test_priority_label_only() {
        let labels = vec!["p1".to_string()];
        let issue = create_test_issue(labels, vec![]);
        let status = check_already_triaged(&issue);
        assert!(!status.is_triaged());
        assert!(!status.has_type_label);
        assert!(status.has_priority_label);
        assert!(!status.has_aptu_comment);
        assert_eq!(status.label_names.len(), 1);
    }

    #[test]
    fn test_type_and_priority_labels() {
        let labels = vec!["bug".to_string(), "p1".to_string()];
        let issue = create_test_issue(labels, vec![]);
        let status = check_already_triaged(&issue);
        assert!(status.is_triaged());
        assert!(status.has_type_label);
        assert!(status.has_priority_label);
        assert!(!status.has_aptu_comment);
        assert_eq!(status.label_names.len(), 2);
    }

    #[test]
    fn test_priority_prefix_labels() {
        // Test all priority: prefix variants (high, medium, low)
        for priority in ["priority: high", "priority: medium", "priority: low"] {
            let labels = vec!["bug".to_string(), priority.to_string()];
            let issue = create_test_issue(labels, vec![]);
            let status = check_already_triaged(&issue);
            assert!(status.is_triaged(), "Failed for {priority}");
            assert!(status.has_type_label, "Failed for {priority}");
            assert!(status.has_priority_label, "Failed for {priority}");
        }
    }

    #[test]
    fn test_aptu_comment_only() {
        let comments = vec![IssueComment {
            id: "1".to_string(),
            author: "aptu-bot".to_string(),
            body: "This looks good. Generated by Aptu".to_string(),
        }];
        let issue = create_test_issue(vec![], comments);
        let status = check_already_triaged(&issue);
        assert!(status.is_triaged());
        assert!(!status.has_type_label);
        assert!(!status.has_priority_label);
        assert!(status.has_aptu_comment);
        assert!(status.label_names.is_empty());
    }

    #[test]
    fn test_type_label_with_aptu_comment() {
        let labels = vec!["bug".to_string()];
        let comments = vec![IssueComment {
            id: "2".to_string(),
            author: "aptu-bot".to_string(),
            body: "Generated by Aptu".to_string(),
        }];
        let issue = create_test_issue(labels, comments);
        let status = check_already_triaged(&issue);
        assert!(status.is_triaged());
        assert!(status.has_type_label);
        assert!(!status.has_priority_label);
        assert!(status.has_aptu_comment);
    }

    #[test]
    fn test_partial_signature_no_match() {
        let comments = vec![IssueComment {
            id: "3".to_string(),
            author: "other-bot".to_string(),
            body: "Generated by AnotherTool".to_string(),
        }];
        let issue = create_test_issue(vec![], comments);
        let status = check_already_triaged(&issue);
        assert!(!status.is_triaged());
        assert!(!status.has_aptu_comment);
    }

    #[test]
    fn test_irrelevant_labels() {
        let labels = vec!["component: ui".to_string(), "needs-review".to_string()];
        let issue = create_test_issue(labels, vec![]);
        let status = check_already_triaged(&issue);
        assert!(!status.is_triaged());
        assert!(!status.has_type_label);
        assert!(!status.has_priority_label);
        assert!(status.label_names.is_empty());
    }

    #[test]
    fn test_priority_label_case_insensitive() {
        let labels = vec!["bug".to_string(), "P2".to_string()];
        let issue = create_test_issue(labels, vec![]);
        let status = check_already_triaged(&issue);
        assert!(status.is_triaged());
        assert!(status.has_priority_label);
    }

    #[test]
    fn test_priority_prefix_case_insensitive() {
        let labels = vec!["enhancement".to_string(), "Priority: HIGH".to_string()];
        let issue = create_test_issue(labels, vec![]);
        let status = check_already_triaged(&issue);
        assert!(status.is_triaged());
        assert!(status.has_priority_label);
    }

    #[test]
    fn test_render_triage_markdown_basic() {
        let triage = TriageResponse {
            summary: "This is a test summary".to_string(),
            implementation_approach: None,
            clarifying_questions: vec!["Question 1?".to_string()],
            potential_duplicates: vec![],
            related_issues: vec![],
            suggested_labels: vec!["bug".to_string()],
            suggested_milestone: None,
            status_note: None,
            contributor_guidance: None,
            complexity: None,
        };

        let markdown = render_triage_markdown(&triage);
        assert!(markdown.contains("## Triage Summary"));
        assert!(markdown.contains("This is a test summary"));
        assert!(markdown.contains("### Clarifying Questions"));
        assert!(markdown.contains("1. Question 1?"));
        assert!(markdown.contains(APTU_SIGNATURE));
    }

    #[test]
    fn test_render_triage_markdown_with_labels() {
        let triage = TriageResponse {
            summary: "Summary".to_string(),
            implementation_approach: None,
            clarifying_questions: vec![],
            potential_duplicates: vec![],
            related_issues: vec![],
            suggested_labels: vec!["bug".to_string(), "p1".to_string()],
            suggested_milestone: None,
            status_note: None,
            contributor_guidance: None,
            complexity: None,
        };

        let markdown = render_triage_markdown(&triage);
        assert!(markdown.contains("### Suggested Labels"));
        assert!(markdown.contains("`bug`"));
        assert!(markdown.contains("`p1`"));
    }

    #[test]
    fn test_render_triage_markdown_multiline_approach() {
        let triage = TriageResponse {
            summary: "Summary".to_string(),
            implementation_approach: Some("Line 1\nLine 2\nLine 3".to_string()),
            clarifying_questions: vec![],
            potential_duplicates: vec![],
            related_issues: vec![],
            suggested_labels: vec![],
            suggested_milestone: None,
            status_note: None,
            contributor_guidance: None,
            complexity: None,
        };

        let markdown = render_triage_markdown(&triage);
        assert!(markdown.contains("### Implementation Approach"));
        assert!(markdown.contains("Line 1"));
        assert!(markdown.contains("Line 2"));
        assert!(markdown.contains("Line 3"));
    }

    fn make_pr_review() -> PrReviewResponse {
        PrReviewResponse {
            summary: "Good PR overall.".to_string(),
            verdict: "approve".to_string(),
            strengths: vec!["Clean code".to_string(), "Good tests".to_string()],
            concerns: vec!["Missing docs".to_string()],
            comments: vec![PrReviewComment {
                file: "src/lib.rs".to_string(),
                line: Some(42),
                comment: "Consider using a match here.".to_string(),
                severity: CommentSeverity::Suggestion,
                suggested_code: None,
            }],
            suggestions: vec!["Add a CHANGELOG entry.".to_string()],
            disclaimer: Some("AI-generated review.".to_string()),
        }
    }

    #[test]
    fn test_render_pr_review_markdown_basic() {
        let review = make_pr_review();
        let body = render_pr_review_markdown(&review, "abc123");
        // Marker is the literal first line.
        assert!(body.starts_with("<!-- APTU_REVIEW:abc123 -->\n"));
        assert!(body.contains("✅ Approved"));
        assert!(body.contains("Good PR overall."));
        assert!(body.contains("aptu"));
        // Structured sections render regardless of files_count.
        assert!(body.contains("### Concerns"));
        assert!(body.contains("<details>"));
        assert!(body.contains("<summary>Strengths</summary>"));
        assert!(body.contains("- Clean code"));
        assert!(body.contains("<summary>Suggestions</summary>"));
        assert!(body.contains("- Add a CHANGELOG entry."));
        assert!(body.contains("- Missing docs"));
    }

    #[test]
    fn test_render_pr_review_markdown_marker_first_line() {
        let review = make_pr_review();
        let body = render_pr_review_markdown(&review, "deadbeef");
        assert_eq!(body.lines().next(), Some("<!-- APTU_REVIEW:deadbeef -->"));
    }

    #[test]
    fn test_render_pr_review_markdown_empty_arrays() {
        let review = PrReviewResponse {
            summary: "LGTM".to_string(),
            verdict: "approve".to_string(),
            strengths: vec![],
            concerns: vec![],
            comments: vec![],
            suggestions: vec![],
            disclaimer: None,
        };
        let body = render_pr_review_markdown(&review, "abc123");
        assert!(body.contains("<!-- APTU_REVIEW:abc123 -->"));
        assert!(!body.contains("Strengths"));
        assert!(!body.contains("Concerns"));
        assert!(!body.contains("Suggestions"));
        assert!(!body.contains("<details>"));
    }

    #[test]
    fn test_render_pr_review_markdown_verdict_badges() {
        let mut r = make_pr_review();
        r.verdict = "approve".to_string();
        assert!(render_pr_review_markdown(&r, "s").contains("✅ Approved"));
        r.verdict = "request_changes".to_string();
        assert!(render_pr_review_markdown(&r, "s").contains("❌ Request Changes"));
        r.verdict = "request-changes".to_string();
        assert!(render_pr_review_markdown(&r, "s").contains("❌ Request Changes"));
        r.verdict = "comment".to_string();
        assert!(render_pr_review_markdown(&r, "s").contains("💬 Comments"));
    }

    fn make_walkthrough_file(filename: &str, additions: u64, deletions: u64) -> PrFile {
        PrFile {
            filename: filename.to_string(),
            status: "modified".to_string(),
            additions,
            deletions,
            patch: None,
            patch_truncated: false,
            full_content: None,
        }
    }

    #[test]
    fn test_render_file_walkthrough_sorted_by_churn() {
        let files = vec![
            make_walkthrough_file("src/small.rs", 1, 0),
            make_walkthrough_file("src/big.rs", 10, 5),
        ];
        let table = render_file_walkthrough(&files).expect("table for non-empty files");
        assert!(table.contains("### Files Changed"));
        assert!(table.contains("| File | Diff |"));
        let big = table.find("src/big.rs").expect("big row");
        let small = table.find("src/small.rs").expect("small row");
        assert!(big < small, "rows sorted by descending churn");
        assert!(table.contains("| src/big.rs | +10 −5 |"));
    }

    #[test]
    fn test_render_file_walkthrough_empty_returns_none() {
        assert!(render_file_walkthrough(&[]).is_none());
    }

    #[test]
    fn test_render_file_walkthrough_caps_at_twenty_rows_with_tail() {
        let files: Vec<PrFile> = (0..23)
            .map(|i| make_walkthrough_file(&format!("f{i}.rs"), i, 0))
            .collect();
        let table = render_file_walkthrough(&files).expect("table");
        assert_eq!(table.matches("| f").count(), 20);
        assert!(table.contains("| ... and 3 more | |"));
    }

    #[test]
    fn test_render_file_walkthrough_removed_file_with_zero_churn() {
        let files = vec![make_walkthrough_file("gone.rs", 0, 0)];
        let table = render_file_walkthrough(&files).expect("table");
        assert!(table.contains("| gone.rs | +0 −0 |"));
    }

    #[test]
    fn test_render_file_walkthrough_escapes_pipes_and_strips_newlines() {
        let files = vec![make_walkthrough_file("we|rd.rs", 1, 0)];
        let table = render_file_walkthrough(&files).expect("table");
        assert!(table.contains("| we\\|rd.rs | +1 −0 |"));

        let files = vec![make_walkthrough_file("bad\r\nname`x.rs", 1, 0)];
        let table = render_file_walkthrough(&files).expect("table");
        assert!(table.contains("| badname\\`x.rs | +1 −0 |"));
        assert!(!table.contains('\r'));

        let files = vec![make_walkthrough_file("a\\b|c.rs", 1, 0)];
        let table = render_file_walkthrough(&files).expect("table");
        assert!(table.contains("| a\\\\b\\|c.rs | +1 −0 |"));
    }

    #[test]
    fn test_render_pr_review_review_body_excludes_summary_and_marker() {
        let review = make_pr_review();
        let files = vec![make_walkthrough_file("src/main.rs", 3, 1)];
        let body = render_pr_review_review_body(&review, &files);
        assert!(!body.contains(REVIEW_SUMMARY_MARKER_PREFIX));
        assert!(!body.contains(&review.summary));
        assert!(body.contains("## Aptu Review"));
        assert!(body.contains("### Concerns"));
        assert!(body.contains("<summary>Strengths</summary>"));
        // Walkthrough table carries stats only; never the summary or marker.
        assert!(body.contains("| src/main.rs | +3 −1 |"));
        // Summary comment remains the single surface carrying the summary text.
        let comment = render_pr_review_markdown(&review, "abc123");
        assert!(comment.contains(&review.summary));
    }

    #[test]
    fn test_render_pr_review_review_body_empty_files_omits_table() {
        let review = make_pr_review();
        let body = render_pr_review_review_body(&review, &[]);
        assert!(!body.contains("### Files Changed"));
    }

    #[test]
    fn test_parse_aptu_summary_marker_with_sha() {
        let marker =
            parse_aptu_summary_marker("<!-- APTU_REVIEW:0123abcd -->\n## Aptu Review\n\nbody");
        assert_eq!(
            marker,
            Some(AptuSummaryMarker {
                sha: Some("0123abcd".to_string())
            })
        );
    }

    #[test]
    fn test_parse_aptu_summary_marker_legacy_sha_less() {
        // Legacy marker (no SHA) parses to sha: None and is treated as stale.
        let marker = parse_aptu_summary_marker("<!-- APTU_REVIEW -->\n## Aptu Review");
        assert_eq!(marker, Some(AptuSummaryMarker { sha: None }));
        // No marker at all.
        assert_eq!(parse_aptu_summary_marker("just a comment"), None);
        // Marker mentioned mid-body is not anchored; prefix match requires start.
        assert_eq!(
            parse_aptu_summary_marker("see <!-- APTU_REVIEW:deadbeef -->"),
            None
        );
    }

    #[test]
    fn test_render_pr_review_comment_body_severity_badges() {
        let base = PrReviewComment {
            file: "f.rs".to_string(),
            line: Some(1),
            comment: "test msg".to_string(),
            severity: CommentSeverity::Issue,
            suggested_code: None,
        };
        let cases = [
            (CommentSeverity::Issue, "🔴"),
            (CommentSeverity::Warning, "🟠"),
            (CommentSeverity::Suggestion, "💡"),
            (CommentSeverity::Info, "🔵"),
        ];
        for (severity, badge) in cases {
            let c = PrReviewComment {
                severity,
                ..base.clone()
            };
            let body = render_pr_review_comment_body(&c);
            assert!(body.contains(badge), "missing badge {badge}");
            assert!(body.contains("test msg"));
            assert!(body.starts_with(REVIEW_COMMENT_MARKER));
            assert!(!body.contains("[!"));
        }
    }

    #[test]
    fn test_render_pr_review_comment_body_with_suggestion() {
        let comment = PrReviewComment {
            file: "src/main.rs".to_string(),
            line: Some(10),
            comment: "Use ? instead of unwrap.".to_string(),
            severity: CommentSeverity::Warning,
            suggested_code: Some("    let x = foo()?;\n".to_string()),
        };
        let body = render_pr_review_comment_body(&comment);
        assert!(body.contains("🟠 Warning: Use ? instead of unwrap."));
        assert!(body.contains("```suggestion"));
        assert!(body.contains("let x = foo()?;"));
    }

    #[test]
    fn test_render_pr_review_comment_body_without_suggestion() {
        let comment = PrReviewComment {
            file: "src/main.rs".to_string(),
            line: Some(10),
            comment: "Consider refactoring this module.".to_string(),
            severity: CommentSeverity::Info,
            suggested_code: None,
        };
        let body = render_pr_review_comment_body(&comment);
        assert!(body.contains("🔵 Info: Consider refactoring this module."));
        assert!(!body.contains("```suggestion"));
    }

    #[test]
    fn test_render_triage_markdown_with_complexity() {
        use crate::ai::types::{ComplexityAssessment, ComplexityLevel};

        // Arrange: triage response with a High complexity assessment
        let triage = TriageResponse {
            summary: "Complex change".to_string(),
            implementation_approach: None,
            clarifying_questions: vec![],
            potential_duplicates: vec![],
            related_issues: vec![],
            suggested_labels: vec![],
            suggested_milestone: None,
            status_note: None,
            contributor_guidance: None,
            complexity: Some(ComplexityAssessment {
                level: ComplexityLevel::High,
                estimated_loc: Some(300),
                affected_areas: vec!["crates/aptu-core/src/retry.rs".to_string()],
                recommendation: Some("Decompose into sub-issues".to_string()),
            }),
        };

        // Act
        let markdown = render_triage_markdown(&triage);

        // Assert: complexity section is present with expected content
        assert!(
            markdown.contains("### Complexity"),
            "markdown must contain complexity section header"
        );
        assert!(
            markdown.contains("High"),
            "markdown must contain complexity level"
        );
        assert!(
            markdown.contains("300"),
            "markdown must contain estimated LOC"
        );
        assert!(
            markdown.contains("Decompose into sub-issues"),
            "markdown must contain recommendation"
        );
    }

    fn hash_comment(comment_text: &str, severity: CommentSeverity, code: Option<&str>) -> String {
        comment_content_hash(&PrReviewComment {
            file: "f.rs".to_string(),
            line: Some(1),
            comment: comment_text.to_string(),
            severity,
            suggested_code: code.map(str::to_string),
        })
    }

    #[test]
    fn test_comment_content_hash_nul_bytes_do_not_collapse() {
        // A comment text containing NUL bytes must not be confusable with a
        // different split of (comment, severity, suggested_code).
        let with_nul = hash_comment("bad\0Warning\0code", CommentSeverity::Issue, None);
        let split = hash_comment("bad", CommentSeverity::Warning, Some("code"));
        assert_ne!(with_nul, split);
        // Empty suggested_code vs. a comment ending in a NUL remain distinct.
        let trailing_nul = hash_comment("bad\0", CommentSeverity::Issue, None);
        let with_empty_code = hash_comment("bad", CommentSeverity::Issue, Some(""));
        assert_ne!(trailing_nul, with_empty_code);
    }

    #[test]
    fn test_comment_content_hash_adversarial_boundary_shift() {
        // Comment plus a code-looking tail must differ from comment with that
        // tail moved into suggested_code (old 0x00 delimiter would collide).
        let merged = hash_comment("msg\0let x = 1;", CommentSeverity::Suggestion, None);
        let shifted = hash_comment("msg", CommentSeverity::Suggestion, Some("let x = 1;"));
        assert_ne!(merged, shifted);
    }

    #[test]
    fn test_comment_content_hash_none_vs_empty_suggested_code() {
        // Presence discriminant: None and Some("") are semantically different
        // and must not collapse to the same hash.
        let none = hash_comment("msg", CommentSeverity::Issue, None);
        let empty = hash_comment("msg", CommentSeverity::Issue, Some(""));
        assert_ne!(none, empty);
    }

    #[test]
    fn test_comment_content_hash_is_deterministic() {
        let a = hash_comment("msg", CommentSeverity::Issue, Some("let x = 1;"));
        let b = hash_comment("msg", CommentSeverity::Issue, Some("let x = 1;"));
        assert_eq!(a, b);
        assert_eq!(a.len(), 64);
    }
}
